version: '3'

services:
  ndd:
    container_name: 'django'
    build:
      context: .
    ports:
      - '8000:8000'
    restart: always
    volumes:
      - ./app:/ndd/app
      - ./log/gunicorn:/log
      - static-data:/ndd/statics
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - GOOGLE_OAUTH2_CLIENT_ID=${GOOGLE_OAUTH2_CLIENT_ID}
      - GOOGLE_OAUTH2_CLIENT_SECRET=${GOOGLE_OAUTH2_CLIENT_SECRET}
      - KAKAO_OAUTH2_CLIENT_ID=${KAKAO_OAUTH2_CLIENT_ID}
      - KAKAO_OAUTH2_CLIENT_SECRET=${KAKAO_OAUTH2_CLIENT_SECRET}
      - HOST=${HOST}
      - DEV=${DEV}
    depends_on:
      - db

  db:
    container_name: 'postgres'
    image: postgres:latest
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - 5432:5432

  proxy:
    container_name: 'nginx'
    build:
      context: ./proxy
    restart: always
    depends_on:
      - ndd
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx/var/lib/letsencrypt:/var/lib/letsencrypt
      - ./app:/ndd/app
      - ./log/nginx:/log
      - static-data:/ndd/statics
    environment:
      - TZ=Asia/Seoul

volumes:
  postgres-data:
  static-data:
