name: deploy-dev-ncp
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH-Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.NCP_SSH_IP}}
          port: ${{secrets.NCP_SSH_PORT}}
          username: ${{secrets.NCP_SSH_ID}}
          password: ${{secrets.NC_SSH_PASSWORD}}
          script: |
            whoami
            cd /root/ndd
            git pull origin develop
            docker compose down
            docker compose build
            docker compose up -d
